version: '3.0'

services:
  spotify-playlist-generator-prod:
    container_name: spotify-playlist-generator-prod
    image: spotify-playlist-generator:latest
    restart: always
    build:
      context: .
      dockerfile: ./Generator/Dockerfile
    depends_on:
      - spotify-playlist-generator-database-prod
    ports:
      - "65005:80"
    environment:
      Telegram:Token:
      Spotify:ClientId:
      Spotify:ClientSecret:
      ApplicationInsights:InstrumentationKey:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      Amazon:QueueUrl:
      Database:ConnectionString:
  spotify-playlist-generator-database-prod:
    container_name: spotify-playlist-generator-database-prod
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /pg/spotify-playlist-generator-prod:/var/lib/postgresql/data