<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>20</NoWarn>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Extensions.fs"/>
    <Compile Include="IncludedPlaylist.fs"/>
    <Compile Include="ExcludedPlaylist.fs"/>
    <Compile Include="IncludedArtist.fs"/>
    <Compile Include="ExcludedArtist.fs"/>
    <Compile Include="Recommenders.fs" />
    <Compile Include="TargetedPlaylist.fs"/>
    <Compile Include="Tracks.fs"/>
    <Compile Include="Preset.fs"/>
    <Compile Include="User.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.21.0"/>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1"/>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2"/>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.fsproj" />
  </ItemGroup>

</Project>
