###
GET http://localhost:7071/api/presets
Authorization: Bearer {{apiToken}}

###
GET http://localhost:7071/api/presets/{{presetId}}
Authorization: Bearer {{apiToken}}

###
POST http://localhost:7071/api/presets
Authorization: Bearer {{apiToken}}
Content-Type: application/json

{
  "name": "Test[0]"
}

###
DELETE http://localhost:7071/api/presets/{{presetId}}
Authorization: Bearer {{apiToken}}